### ISSUE TITLE
0 apparently is not always the main module

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#282]
```
socc-pair --crash-id=3f131f66-733d-43f7-8005-c6f700211109
```

```diff
-  did not match
+  main_module: 4
-  main_module: 0
```

https://github.com/luser/rust-minidump/blob/53a3c873869e72339579a9ea402cf48994da9bb3/minidump-processor/src/process_state.rs#L640-L641

(the line marked with + is always what socorro had)

**Comment by luser** [comment]
That assumption comes from here:
https://chromium.googlesource.com/breakpad/breakpad/+/fe35cd43f2c7386704837b686f91a4e3c882664d/src/processor/minidump.cc#2887

Maybe something odd is happening in the translation?

**Comment by Gankra** [comment]
Seems vaguely relevant: https://searchfox.org/mozilla-central/source/toolkit/crashreporter/minidump-analyzer/minidump-analyzer.cpp#262-283


```
  int mainModuleIndex = -1;

  for (const auto& itr : aOrderedModules) {
    const CodeModule* module = itr.first;

    if ((module->base_address() == mainAddress) && mainModule) {
      mainModuleIndex = itr.second;
    }

    Json::Value moduleNode;
    moduleNode["filename"] = PathnameStripper::File(module->code_file());
    moduleNode["code_id"] = PathnameStripper::File(module->code_identifier());
    moduleNode["version"] = module->version();
    moduleNode["debug_file"] = PathnameStripper::File(module->debug_file());
    moduleNode["debug_id"] = module->debug_identifier();
    moduleNode["base_addr"] = ToHex(module->base_address());
    moduleNode["end_addr"] = ToHex(module->base_address() + module->size());

    aNode.append(moduleNode);
  }

  return mainModuleIndex;
  ```

**Comment by luser** [comment]
I overlooked the fact that you included the crash id in your comment, it's [this crash](https://crash-stats.mozilla.org/report/index/3f131f66-733d-43f7-8005-c6f700211109). The first 4 entries in the module list are:

```yaml
"modules": [

    -
    {
        "base_addr": "0x0000000010000000",
        "code_id": "56E691CC31d000",
        "debug_file": "aetpkss1.pdb",
        "debug_id": "AEC5AECCBFD64867ACC4003E83EAE2F51",
        "end_addr": "0x000000001031d000",
        "filename": "aetpkss1.dll",
        "missing_symbols": true,
        "version": "3.0.0.3930"
    },
    -
    {
        "base_addr": "0x0000000054510000",
        "cert_subject": "Microsoft Corporation",
        "code_id": "5DB2744Ba3000",
        "debug_file": "msvcr90.amd64.pdb",
        "debug_id": "AE4A1A8587F546DB8138E77B0CFBC5611",
        "end_addr": "0x00000000545b3000",
        "filename": "msvcr90.dll",
        "version": "9.0.30729.9625"
    },
    -
    {
        "base_addr": "0x0000000054fb0000",
        "cert_subject": "Microsoft Windows",
        "code_id": "5DB26BCA109000",
        "debug_file": "msvcp80.AMD64.pdb",
        "debug_id": "659FFD99332E458591F9143A25D8F5E61",
        "end_addr": "0x00000000550b9000",
        "filename": "msvcp80.dll",
        "version": "8.0.50727.9672"
    },
    -
    {
        "base_addr": "0x0000000055300000",
        "cert_subject": "Microsoft Windows",
        "code_id": "5DB26B72c9000",
        "debug_file": "msvcr80.AMD64.pdb",
        "debug_id": "C6D7723A01A74C229F64B60A86B4448D1",
        "end_addr": "0x00000000553c9000",
        "filename": "msvcr80.dll",
        "version": "8.0.50727.9672"
    },
    -
    {
        "base_addr": "0x00007ff76e630000",
        "cert_subject": "Mozilla Corporation",
        "code_id": "6189ABF89c000",
        "debug_file": "firefox.pdb",
        "debug_id": "1393648D428E18F24C4C44205044422E1",
        "end_addr": "0x00007ff76e6cc000",
        "filename": "firefox.exe",
        "loaded_symbols": true,
        "symbol_disk_cache_hit": true,
        "symbol_url": "https://symbols.mozilla.org/try/firefox.pdb/1393648D428E18F24C4C44205044422E1/firefox.sym",
        "version": "96.0.0.7982"
    },
]
}
```

Wild! This is from Windows, too, so this is something Microsoft's minidump writer produced. That first DLL [appears to be a PKCS#11 provider](https://github.com/t-d-k/LibreCrypt/blob/master/docs/pkcs11_drivers.md#appendix-e-pkcs11-driver-libraries)?
